version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praiser
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: praiser
      DB_USERNAME: root
      DB_PASSWORD: root
